fortunecookie = [
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A feather in the hand is better than a bird in the air.",
    "A fresh start will put you on your way.",
    "A friend asks only for your time not your money.",
    "A friend is a present you give yourself.",
    "A gambler not only will lose what he has, but also will lose what he doesn’t have.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good friendship is often more important than a passionate romance.",
    "A good time to finish up old tasks.",
    "A hunch is creativity trying to tell you something.",
    "A lifetime friend shall soon be made.",
    "A lifetime of happiness lies ahead of you.",
    "A light heart carries you through all the hard times.",
    "A new perspective will come with the new year.",
    "A person is never too old to learn.",
    "A person of words and not deeds is like a garden full of weeds.",
    "A pleasant surprise is waiting for you.",
    "A short pencil is usually better than a long memory any day.",
    "A small donation is call for. It’s the right thing to do.",
    "A smile is your personal welcome mat.",
    "A smooth long journey! Great expectations.",
    "A soft voice may be awfully persuasive.",
    "A truly rich life contains love and art in abundance.",
    "Accept something that you cannot change, and you will feel better.",
    "Adventure can be real happiness.",
    "Advice is like kissing. It costs nothing and is a pleasant thing to do.",
    "Advice, when most needed, is least heeded.",
    "All the effort you are making will ultimately pay off.",
    "All the troubles you have will pass away very quickly.",
    "All will go well with your new project.",
    "All your hard work will soon pay off.",
    "Allow compassion to guide your decisions.",
    "An acquaintance of the past will affect you in the near future.",
    "An agreeable romance might begin to take on the appearance.",
    "An important person will offer you support.",
    "An inch of time is an inch of gold.",
    "Any day above ground is a good day.",
    "Any decision you have to make tomorrow is a good decision.",
    "At the touch of love, everyone becomes a poet.",
    "Be careful or you could fall for some tricks today.",
    "Beauty in its various forms appeals to you.",
    "Because you demand more from yourself, others respect you deeply.",
    "Believe in yourself and others will too.",
    "Believe it can be done.",
    "Better ask twice than lose yourself once.",
    "Bide your time, for success is near.",
    "Carve your name on your heart and not on marble.",
    "Chance favors those in motion.",
    "Change is happening in your life, so go with the flow!",
    "Competence like yours is underrated.",
    "Congratulations! You are on your way.",
    "Could I get some directions to your heart?",
    "Courtesy begins in the home.",
    "Courtesy is contagious.",
    "Curiosity kills boredom. Nothing can kill curiosity.",
    "Dedicate yourself with a calm mind to the task at hand.",
    "Depart not from the path which fate has you assigned.",
    "Determination is what you need now.",
    "Diligence and modesty can raise your social status.",
    "Disbelief destroys the magic.",
    "Distance yourself from the vain.",
    "Do not be intimidated by the eloquence of others.",
    "Do not demand for someone’s soul if you already got his heart.",
    "Do not let ambitions overshadow small success.",
    "Do not make extra work for yourself.",
    "Do not underestimate yourself. Human beings have unlimited potentials.",
    "Do you know that the busiest person has the largest amount of time?",
    "Don’t be discouraged, because every wrong attempt discarded is another step forward.",
    "Don’t confuse recklessness with confidence.",
    "Don’t expect romantic attachments to be strictly logical or rational.",
    "Don’t just spend time. Invest it.",
    "Don’t just think, act!",
    "Don’t let friends impose on you, work calmly and silently.",
    "Don’t let the past and useless detail choke your existence.",
    "Don’t let your limitations overshadow your talents.",
    "Don’t worry; prosperity will knock on your door soon.",
    "Each day, compel yourself to do something you would rather not do.",
    "Education is the ability to meet life’s situations.",
    "Embrace this love relationship you have!",
    "Emulate what you admire in your parents.",
    "Emulate what you respect in your friends.",
    "Every flower blooms in its own sweet time.",
    "Every wise man started out by asking many questions.",
    "Everyday in your life is a special occasion.",
    "Everywhere you choose to go, friendly faces will greet you.",
    "Expect much of yourself and little of others.",
    "Failure is the chance to do better next time.",
    "Failure is the path of lease persistence.",
    "Fear and desire – two sides of the same coin.",
    "Fearless courage is the foundation of victory.",
    "Feeding a cow with roses does not get extra appreciation.",
    "First think of what you want to do; then do what you have to do.",
    "Follow the middle path. Neither extreme will make you happy.",
    "For hate is never conquered by hate. Hate is conquered by love.",
    "For the things we have to learn before we can do them, we learn by doing them.",
    "From listening comes wisdom and from speaking repentance.",
    "From now on your kindness will lead you to success.",
    "Get your mind set – confidence will lead you on.",
    "Go for the gold today! You’ll be the champion of whatever.",
    "Go take a rest; you deserve it.",
    "Good news will be brought to you by mail.",
    "Good news will come to you by mail.",
    "Good to begin well, better to end well.",
    "Happiness begins with facing life with a smile and a wink.",
    "Happiness will bring you good luck.",
    "Happy life is just in front of you.",
    "Hard words break no bones, fine words butter no parsnips.",
    "Have a beautiful day.",
    "He who expects no gratitude shall never be disappointed.",
    "He who knows he has enough is rich.",
    "He who knows others is wise. He who knows himself is enlightened.",
    "How you look depends on where you go.",
    "I learn by going where I have to go.",
    "If a true sense of value is to be yours it must come through service.",
    "If certainty were truth, we would never be wrong.",
    "If you continually give, you will continually have.",
    "If you look in the right places, you can find some good offerings.",
    "If you think you can do a thing or think you can’t do a thing, you’re right.",
    "If you wish to see the best in others, show the best of yourself.",
    "If your desires are not extravagant, they will be granted.",
    "If your desires are not to extravagant they will be granted.",
    "If you’re feeling down, try throwing yourself into your work.",
    "Imagination rules the world.",
    "In order to take, one must first give.",
    "In the end all things will be known.",
    "In this world of contradiction, It’s better to be merry than wise.",
    "It could be better, but its [sic] good enough.",
    "It is better to be an optimist and proven a fool than to be a pessimist and be proven right.",
    "It is better to deal with problems before they arise.",
    "It is honorable to stand up for what is right, however unpopular it seems.",
    "It is worth reviewing some old lessons.",
    "It takes courage to admit fault.",
    "It’s not the amount of time you devote, but what you devote to the time that counts.",
    "It’s time to get moving. Your spirits will lift accordingly.",
    "Keep your face to the sunshine and you will never see shadows.",
    "Let the world be filled with tranquility and goodwill.",
    "Like the river flow into the sea. Something are just meant to be.",
    "Listen not to vain words of empty tongue.",
    "Listen to everyone. Ideas come from everywhere.",
    "Living with a commitment to excellence shall take you far.",
    "Long life is in store for you.",
    "Love is a warm fire to keep the soul warm.",
    "Love is like sweet medicine, good to the last drop.",
    "Love lights up the world.",
    "Love truth, but pardon error.",
    "Man is born to live and not prepared to live.",
    "Man’s mind, once stretched by a new idea, never regains it’s original dimensions.",
    "Many will travel to hear you speak.",
    "Meditation with an old enemy is advised.",
    "Miles are covered one step at a time.",
    "Nature, time and patience are the three great physicians.",
    "Never fear! The end of something marks the start of something new.",
    "New ideas could be profitable.",
    "New people will bring you new realizations, especially about big issues.",
    "No one can walk backwards into the future.",
    "Nothing is more difficult, and therefore more precious, than to be able to decide.",
    "Now is a good time to buy stock.",
    "Now is the time to go ahead and pursue that love interest!",
    "Now is the time to try something new",
    "Now is the time to try something new.",
    "Observe all men, but most of all yourself.",
    "One can never fill another’s shoes, rather he must outgrow the old shoes.",
    "One of the first things you should look for in a problem is its positive side.",
    "Others can help you now.",
    "Pennies from heaven find their way to your doorstep this year!",
    "People are attracted by your delicate features.",
    "People find it difficult to resist your persuasive manner.",
    "Perhaps you’ve been focusing too much on saving.",
    "Physical activity will dramatically improve your outlook today.",
    "Pick battles big enough to matter, small enough to win.",
    "Place special emphasis on old friendship.",
    "Please visit us at www.wontonfood.com",
    "Practice makes perfect.",
    "Protective measures will prevent costly disasters.",
    "Put your mind into planning today. Look into the future.",
    "Remember the birthday but never the age.",
    "Remember to share good fortune as well as bad with your friends.",
    "Rest has a peaceful effect on your physical and emotional health.",
    "Resting well is as important as working hard.",
    "Romance moves you in a new direction.",
    "Savor your freedom – it is precious.",
    "Say hello to others. You will have a happier day.",
    "Self-knowledge is a life long process.",
    "Share your joys and sorrows with your family.",
    "Sift through your past to get a better idea of the present.",
    "Sloth makes all things difficult; industry all easy.",
    "Small confidences mark the onset of a friendship.",
    "Society prepares the crime; the criminal commits it.",
    "Someone you care about seeks reconciliation.",
    "Soon life will become more interesting.",
    "Stand tall. Don’t look down upon yourself.",
    "Staying close to home is going to be best for your morale today",
    "Stop searching forever, happiness is just next to you.",
    "Strong reasons make strong actions.",
    "Success is a journey, not a destination.",
    "Success is failure turned inside out.",
    "Success is going from failure to failure without loss of enthusiasm.",
    "Swimming is easy. Stay floating is hard.",
    "Take care and sensitivity you show towards others will return to you.",
    "Take the high road.",
    "Technology is the art of arranging the world so we do not notice it.",
    "The austerity you see around you covers the richness of life like a veil.",
    "The best prediction of future is the past.",
    "The change you started already have far-reaching effects. Be ready.",
    "The first man gets the oyster, the second man gets the shell.",
    "The greatest achievement in life is to stand up again after falling.",
    "The harder you work, the luckier you get.",
    "The night life is for you.",
    "The one that recognizes the illusion does not act as if it is real.",
    "The only people who never fail are those who never try.",
    "The person who will not stand for something will fall for anything.",
    "The philosophy of one century is the common sense of the next.",
    "The saints are the sinners who keep on trying.",
    "The secret to good friends is no secret to you.",
    "The small courtesies sweeten life, the greater ennoble it.",
    "The smart thing to do is to begin trusting your intuitions.",
    "The strong person understands how to withstand substantial loss.",
    "The sure way to predict the future is to invent it.",
    "The truly generous share, even with the undeserving.",
    "The value lies not within any particular thing, but in the desire placed on that thing.",
    "The weather is wonderful.",
    "There is a time for caution, but not for fear.",
    "There is no mistake so great as that of being always right.",
    "There is no wisdom greater than kindness.",
    "There is not greater pleasure than seeing your loved ones prosper.",
    "There’s no such thing as an ordinary cat.",
    "Things don’t just happen; they happen just.",
    "Those who care will make the effort.",
    "Time and patience are called for many surprises await you!.",
    "Time is precious, but truth is more precious than time",
    "To know oneself, one should assert oneself.",
    "To the world you may be one person, but to one person you may be the world.",
    "Today is the conserve yourself, as things just won’t budge.",
    "Today, your mouth might be moving but no one is listening.",
    "Tonight you will be blinded by passion.",
    "Use your eloquence where it will do the most good.",
    "We first make our habits, and then our habits make us.",
    "Welcome change.",
    "“Welcome” is a powerful word.",
    "Well done is better than well said.",
    "What’s hidden in an empty box?",
    "What’s that in your eye? Oh…it’s a sparkle.",
    "What’s yours in mine, and what’s mine is mine.",
    "When more become too much. It’s same as being not enough.",
    "When your heart is pure, your mind is clear.",
    "Wish you happiness.",
    "With age comes wisdom.",
    "Your adventure could lead to happiness.",
    "You always bring others happiness.",
    "You are a person of another time.",
    "You are a talented storyteller. ",
    "You are admired by everyone for your talent and ability.",
    "You are almost there.",
    "You are busy, but you are happy.",
    "You are generous to an extreme and always think of the other fellow.",
    "You are going to have some new clothes. ",
    "You are in good hands this evening.",
    "You are interested in higher education, whether material or spiritual.",
    "You are modest and courteous.",
    "You are never selfish with your advice or your help.",
    "You are next in line for promotion in your firm.",
    "You are offered the dream of a lifetime. Say yes!",
    "You are open-minded and quick to make new friends. ",
    "You are solid and dependable.",
    "You are soon going to change your present line of work.",
    "You are talented in many ways.",
    "You are the master of every situation. ",
    "You are very expressive and positive in words, act and feeling.",
    "You are working hard.",
    "You begin to appreciate how important it is to share your personal beliefs.",
    "You can keep a secret.",
    "You can see a lot just by looking.",
    "You can’t steal second base and keep your foot on first.",
    "You desire recognition and you will find it.",
    "You have a deep appreciation of the arts and music.",
    "You have a deep interest in all that is artistic.",
    "You have a friendly heart and are well admired. ",
    "You have a shrewd knack for spotting insincerity.",
    "You have a yearning for perfection.",
    "You have an active mind and a keen imagination.",
    "You have an ambitious nature and may make a name for yourself.",
    "You have an unusual equipment for success, use it properly.",
    "You have exceeded what was expected.",
    "You have had a good start. Work harder!",
    "You have the power to write your own fortune.",
    "You have yearning for perfection.",
    "You know where you are going and how to get there.",
    "You look pretty.",
    "You love challenge.",
    "You make people realize that there exist other beauties in the world.",
    "You never hesitate to tackle the most difficult problems. ",
    "You never know who you touch.",
    "You only treasure what you lost.",
    "You seek to shield those you love and like the role of provider. ",
    "You should be able to make money and hold on to it.",
    "You should be able to undertake and complete anything.",
    "You understand how to have fun with others and to enjoy your solitude.",
    "You will always be surrounded by true friends.",
    "You will always get what you want through your charm and personality.",
    "You will always have good luck in your personal affairs.",
    "You will be a great success both in the business world and society. ",
    "You will be blessed with longevity.",
    "You will be pleasantly surprised tonight.",
    "You will be sharing great news with all the people you love.",
    "You will be successful in your work.",
    "You will be traveling and coming into a fortune.",
    "You will be unusually successful in business.",
    "You will become a great philanthropist in your later years.",
    "You will become more and more wealthy.",
    "You will enjoy good health.",
    "You will enjoy good health; you will be surrounded by luxury.",
    "You will find great contentment in the daily, routine activities.",
    "You will have a fine capacity for the enjoyment of life.",
    "You will have gold pieces by the bushel.",
    "You will inherit a large sum of money.",
    "You will make change for the better.",
    "You will soon be surrounded by good friends and laughter.",
    "You will take a chance in something in near future.",
    "You will travel far and wide, both pleasure and business.",
    "Your abilities are unparalleled.",
    "Your ability is appreciated.",
    "Your ability to juggle many tasks will take you far.",
    "Your biggest virtue is your modesty.",
    "Your character can be described as natural and unrestrained.",
    "Your difficulties will strengthen you.",
    "Your dreams are never silly; depend on them to guide you.",
    "Your dreams are worth your best efforts to achieve them.",
    "Your energy returns and you get things done.",
    "Your family is young, gifted and attractive.",
    "Your first love has never forgotten you.",
    "Your goal will be reached very soon.",
    "Your happiness is before you, not behind you! Cherish it.",
    "Your hard work will payoff today.",
    "Your heart will always make itself known through your words.",
    "Your home is the center of great love.",
    "Your ideals are well within your reach.",
    "Your infinite capacity for patience will be rewarded sooner or later.",
    "Your leadership qualities will be tested and proven.",
    "Your life will be happy and peaceful.",
    "Your life will get more and more exciting.",
    "Your love life will be happy and harmonious.",
    "Your love of music will be an important part of your life.",
    "Your loyalty is a virtue, but not when it’s wedded with blind stubbornness.",
    "Your mentality is alert, practical, and analytical.",
    "Your mind is creative, original and alert.",
    "Your mind is your greatest asset.",
    "Your moods signal a period of change.",
    "Your quick wits will get you out of a tough situation.",
    "Your reputation is your wealth.",
    "Your success will astonish everyone. ",
    "Your talents will be recognized and suitably rewarded.",
    "Your work interests can capture the highest status or prestige.",
    "Accept yourself.",
    "Be a generous friend and a fair enemy.",
    "A bargain is something you don't need at a price you can't resist.",
    "A beautiful, smart, and loving person will be coming into your life.",
    "A big fortune will descend upon you this year.",
    "A bird in the hand is worth three in the bush",
    "A chance meeting opens new doors to success and friendship.",
    "A cheerful message is on its way to you.",
    "A clear conscience is usually the sign of a bad memory.",
    "A different world cannot be build by indifferent people.",
    "A dream you have will come true.",
    "A feeling is an idea with roots.",
    "A focused mind is one of the most powerful forces in the universe.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good time to finish up old tasks.",
    "A great pleasure in life is doing what others say you can't.",
    "A human being is a deciding being.",
    "A journey of a thousand miles begins with a single step.",
    "A kind word will keep someone warm for years.",
    "A letter of great importance may reach you any day now.",
    "A lifetime of happiness is in store for you.",
    "A man without aim is like a clock without hands, as useless if it turns as if it stands.",
    "A merry heart does good like a medicine.",
    "A new business venture is on the horizon.",
    "A new friend helps you break out of an old routine.",
    "A new outlook brightens your image and brings new friends.",
    "A new voyage will fill your life with untold memories.",
    "A pleasant experience is ahead: don't pass it by.",
    "A pleasant surprise is in store for you tonight.",
    "A short stranger will soon enter your life with blessings to share.",
    "A single conversation with a wise man is better than ten years of study.",
    "A single kind work will keep one warm for years.",
    "A smile is your passport into the hearts of others.",
    "A stranger is a friend you have not spoken to yet.",
    "A thrilling time is in store for you.",
    "A truly great person never puts away the simplicity of a child.",
    "A well-aimed spear is worth three.",
    "A wish is what makes life happen when you dream of rose petals.",
    "Accept something that you cannot change, and you will feel better.",
    "Accept what comes to you each day.",
    "Accept your past without regrets. Handle your present with confidence. Face your future without fear.",
    "Acting is not lying. It is findind someone hiding inside you and letting that person run free.",
    "Action speaks nothing, without the motive.",
    "Adjust finances, make budgets, to improve your standing.",
    "Adversity is the parent of virtue.",
    "Affirm it, visualize it, believe it, and it will actualize itself.",
    "Aim high, time flies.",
    "Alas! The onion you are eating is someone else’s water lily.",
    "All comes at the proper time to him who knows how to wait.",
    "All progress occurs because people dare to be different.",
    "All the preparation you've done will finally be paying off!",
    "All the water in the world can't sink a ship unless it gets inside.",
    "All the world may not love a lover but they will be watching him.",
    "All troubles you have can pass away very quickly.",
    "All your fingers can't be of the same length.",
    "All your sorrows will vanish.",
    "An admirer is concealing their affection for you.",
    "An understanding heart warms all that are graced with its presense.",
    "An unexpected aquaintance will resurface.",
    "An unexpected relationship will become permanent.",
    "An upward movement initiated in time can counteract fate.",
    "Anyone who dares to be, can never be weak.",
    "Anything you do, do it well. The last thing you want is to be sorry for what you didn't do.",
    "Ask a friend to join you on your next voyage.",
    "Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.",
    "Be a good friend and a fair enemy.",
    "Be assertive when decisive action is needed.",
    "Be direct, usually one can accomplish more that way.",
    "Be most affectionate today.",
    "Be patient: in time, even an egg will walk.",
    "Be prepared for extra energy.",
    "Beauty is simply beauty. Originality is magical.",
    "Become who you are.",
    "Before the beginning of great brilliance, there must be chaos.",
    "Before trying to please others think of what makes you happy.",
    "Before you can be reborn you must die.",
    "Before you wonder 'Am I doing things right,'' ask 'Am I doing the right things?'",
    "Begin your life anew with strength, grace and wonder.",
    "Being alone and being lonely are two different things.",
    "Being happy is not always being perfect.",
    "Believing that you are beautiful will make you appear beautiful to others around you.",
    "Bend the rod while it is still hot.",
    "Benefit by doing things that others give up on.",
    "Better be the head of a chicken than the tail of an ox.",
    "Birds are entangled by their feet and men by their tongues.",
    "Bread today is better than cake tomorrow.",
    "Change can hurt, but it leads a path to something better.",
    "Change your thoughts and you change the world.",
    "Circumstance does not make the man; it reveals him to himself.",
    "Compassion is a way of being.",
    "Compassion will cure more then condemnation.",
    "Conquer your fears or they will conquer you.",
    "Constant grinding can turn an iron nod into a needle.",
    "Consume less. Share more. Enjoy life.",
    "Cooperate with those who have both knowledge and integrity.",
    "Demonstrate refinement in everything you do.",
    "Determination is the wake-up call to the human will.",
    "Difficulty at the beginning useually means ease at the end.",
    "Discover the power within yourself.",
    "Do not be overly judgemental of your loved one's intentions or actions.",
    "Do not fear what you don't know",
    "Do not follow where the path may lead. Go where there is no path, and leave a trail",
    "Do not hesitate to look for help, an extra hand should always be welcomed.",
    "Do not let what you do not have prevent you from using what you do have.",
    "Do not seek so much to find the answer as much as to understand the question better.",
    "Your endurance and persistence will be rewarded.",
    "Don't 'face' reality, let it be the place from which you leap.",
    "Don't find fault, find a remedy",
    "Don't just spend time, invest it.",
    "Don't pursue happiness - create it.",
    "Don't take yourself so seriously, no one else does.",
    "Don't wait for your ship to come in, swim out to it",
    "Don't worry about the stock market. Invest in family.",
    "Don't worry about things in the past, there is nothing you can do about them now. Don't worry about things that are happening now, make the best of a bad situation. Don't worry about things in the future, they may never happen.",
    "Dream lofty dreams, and as you dream, so shall you become.",
    "Eat something you never tried before.",
    "Elegant surroundings will soon be yours.",
    "Emotion is energy in motion.",
    "Encourage your peers.",
    "Enjoy life! It is better to be happy than wise.",
    "Enjoy the good luck a companion brings you.",
    "Enthusiastic leadership gets you a promotion when you least expect it.",
    "Even though it will often be difficult and complicated, you know you have what it takes to get it done.",
    "Every day is a new day. But tomorrow is never promised.",
    "Everybody feels lucky for having you as a friend.",
    "Everyone agrees, you are the best.",
    "Everything has beauty but not everyone sees it.",
    "Everything will be ok. Don't obsess. Time will prove you right, you must stay where you are.",
    "Everything will come your way.",
    "Excellence is the difference between what I do and what I am capable of.",
    "Excuses are easy to manufacture, and hard to sell.",
    "Expect great things and great things will come",
    "Express yourself: Don't hold back!",
    "Face facts with dignity.",
    "Failure is not defeat until you stop trying.",
    "Failure is only the opportunity to begin again more intelligently.",
    "Fear is just excitement in need of an attitude adjustment.",
    "Find a peaceful place where you can make plans for the future.",
    "Finish your work on hand don't be greedy.",
    "Follow your bliss and the Universe will open doors where there were once only walls.",
    "For success today, look first to yourself.",
    "Forgive your enemies, but never forget them.",
    "Fortune favors the brave.",
    "Fortune smiles upon you today.",
    "Friends long absent are coming back to you.",
    "Friendship is an ocean that you cannot see bottom.",
    "Generosity will repay itself sooner than you imagine.",
    "Get off to a new start - come out of your shell.",
    "Give yourself some peace and quiet for at least a few hours.",
    "Go confidently in the direction of your dreams.",
    "Going with the flow will make your transition ever so much easier.",
    "Good beginning is half done.",
    "Good health will be yours for a long time.",
    "Good news from afar may bring you a welcome visitor.",
    "good things take time",
    "Grant yourself a wish this year only you can do it.",
    "Great thoughts come from the heart.",
    "Great works are performed not by strength, but by perseverance.",
    "Happinees comes from a good life.",
    "Happiness is an activity.",
    "Happiness is not the absence of conflict, but the ability to cope with it.",
    "Happiness is often a rebound from hard work.",
    "Happiness isn't something you remember, it's something you experience.",
    "Hard words break no bones, fine words butter no parsnips.",
    "Hard work pays off in the future, laziness pays off now.",
    "He who climbs a ladder must begin at the first step.",
    "Help is always needed but not always appreciated. Stay true to your heart and help those in need weather they appreciate it or not.",
    "Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.",
    "Hold on to the past but eventually, let the times go and keep the memories into the present.",
    "Hone your competitive instincts.",
    "Hope brings about a better future",
    "Hope is like food. You will starve without it.",
    "How can you have a beautiful ending without making beautiful mistakes?",
    "Humor usually works at the moment of awkwardness.",
    "I hear and I forget. I see and I remember. I do and I understand.",
    "if you love someone a lot tell them before it's too late",
    "If you love someone keep fighting for them",
    "If winter comes, can spring be far behind?",
    "If you are afraid to shake the dice, you will never throw a six.",
    "If you are never patient, you will never get anything done. If you believe you can do it, you will be rewarded with success.",
    "If you don t give something, you will not get anything",
    "If you don’t do it excellently, don’t do it at all.",
    "If you feel you are right, stand firmly by your convictions.",
    "If you have something good in your life, don't let it go!",
    "If you have something worth fighting for, then fight for it.",
    "If you never expect anything you can never be disappointed.",
    "If you never give up on love, It will never give up on you.",
    "If you refuse to accept anything but the best, you very often get it.",
    "If you speak honestly, everyone will listen.",
    "If you take a single step to your journey, you will succeed",
    "If you want the rainbow, you have to tolerate the rain.",
    "If your desires are not extravagant, they will be granted",
    "Impossible is a word only to be found in the dictionary of fools.",
    "Impossible standards just make life difficult.",
    "In human endeavor, chance favors the prepared mind.",
    "IN ORDER TO GET THE RAINBOW, YOU MUST ENDURE THE RAIN.",
    "In the eyes of lovers, everything is beautiful.",
    "In this life it is not what we take up, but what we give up, that makes us rich.",
    "Instead of worrying and agonizing, move ahead constructively.",
    "Integrity is doing the right thing, even if nobody is watching.",
    "Integrity is the essence of everything successful.",
    "Intelligence is the door to freedom and alert attention is the mother of intelligence.",
    "It is best to act with confidence, no matter how little right you have to it.",
    "It is better to have a hen tomorrow than an egg today.",
    "It is much easier to be critical than to be correct.",
    "It is much easier to look for the bad, than it is to find the good",
    "It is never too late. Just as it is never too early.",
    "It is not necessary to show others you have change; the change will be obvious.",
    "It is now, and in this world, that we must live.",
    "It is very possible that you will achieve greatness in your lifetime.",
    "It may be those who do most, dream most",
    "It never pays to kick a skunk.",
    "It takes more than good memory to have good memories.",
    "It's about time you asked that special someone on a date.",
    "It's better to be alone sometimes.",
    "It's kind of fun to do the impossible",
    "It's never crowded along the extra mile",
    "It's Never Too Late For Good Things To Happen!",
    "It's the worst of times, you need to summon your optimism.",
    "It's tough to be fascinating.",
    "Its amazing how much good you can do if you dont care who gets the credit.",
    "Jealousy doesn't open doors, it closes them!",
    "Judge each day not by the harvest you reap but by the seeds you plant.",
    "Judge not according to the appearance.",
    "Keep it simple. The more you say, the less people remember.",
    "Keep true to the dreams of your youth.",
    "Keep your eye out for someone special.",
    "Keep your eyes open. You never know what you might see.",
    "Keep your feet on the ground even though friends flatter you.",
    "Keep your plans secret for now.",
    "Kiss is not a kiss without the heart.",
    "Land is always on the mind of a flying bird.",
    "Laughter is the shortest distance between two people.",
    "Let not your hand be stretched out to receive and shut when you should repay.",
    "Let the deeds speak.",
    "Let your fantasies unwind...",
    "Let your heart make your decisions - it does not get as confused as your head.",
    "Let your imagination wander.",
    "Let's finish this up now, someone is waiting for you on that",
    "Life always gets harder near the summit.",
    "Life consists not in holding good cards, but in playing those you hold well.",
    "Life does not get better by chance. It gets better by change.",
    "Life is too short to hold grudges.",
    "Life is too short to waste time hating anyone.",
    "Life to you is a dashing and bold adventure",
    "Listen to life, and you will hear the voice of life crying, Be!",
    "Listen to yourself more often",
    "Live each day well and wisely",
    "Live like you are on the bottom, even if you are on the top.",
    "Love because it is the only true adventure.",
    "Love can last a lifetime, if you want it to.",
    "Love can turn cottage into a golden palace.",
    "Love Conquers all.",
    "Love is as necessary to human beings as food and shelter.",
    "Love Is At Your Hands Be Glad And Hold On To It.",
    "Love is free. Lust will cost you everything you have.",
    "Love is on its way.",
    "Love will lead the way.",
    "Luck sometimes visits a fool, but it never sits down with him.",
    "Make a wise choice everyday.",
    "Make all you can, save all you can, give all you can.",
    "Make the system work for you, not the other way around.",
    "Man is born to live and not prepared to live",
    "Many folks are about as happy as they make up their minds to be.",
    "May you have great luck.",
    "Meeting adversity well is the source of your strength.",
    "Minor aches today are likely to pay off handsomely tomorrow.",
    "Money will come to you when you are doing the right thing.",
    "Never bring unhappy feelings into your home.",
    "Never cut what you can untie.",
    "Never give up on someone that you don't go a day without thinking about.",
    "Never give up. Always find a reason to keep trying.",
    "Never give up. You're not a failure if you don't give up.",
    "Never miss a chance to keep your mouth shut.",
    "Never regret anything that made you smile.",
    "Never trouble trouble till trouble troubles you.",
    "Never underestimate the power of the human touch.",
    "Never upset the driver of the car you're in; they're the master of your destiny until you get home.",
    "Next full moon brings an enchanting evening.",
    "Next time you have the opportunity, go on a rollercoaster.",
    "No distance is too far, if two hearts are tied together.",
    "No matter what your past has been, you have a spotless future.",
    "Not all closed eye is sleeping, nor open eye is seeing.",
    "Nothing in the world is accomplished without passion.",
    "Nothing is as good or bad as it appears.",
    "Nothing seems impossible to you.",
    "Nothing Shows A Man's Character More Than What He Laughs At.",
    "Now is the time to try something new.",
    "Old friends make best friends.",
    "That one is not sleeping does not mean they are awake.",
    "One of the best ways to persuade others is with your ears--by listening to them.",
    "One who admires you greatly is hidden before your eyes.",
    "Ones always regrets what could have done. Remember for next time.",
    "Only talent people get help from others.",
    "Open up your heart - it can always be closed again.",
    "Others enjoy your company.",
    "Our deeds determine us, as much as we determine our deeds.",
    "Our duty,as men and women,is to proceed as if limits to our ability did not exist.",
    "Our perception and attitude toward any situation will determine the outcome",
    "Out of confusion comes new patterns.",
    "Over self-confidence is equal to being blind.",
    "Patience is a key to joy.",
    "Patience is a virtue, unless its against a brick wall.",
    "Patience is bitter, but its fruit is sweet.",
    "Patience is key, a wait short or long will have its reward.",
    "People are naturally attracted to you.",
    "People enjoy having you around. Appreciate this.",
    "People in your surroundings will be more cooperative than usual.",
    "People who are late are often happier than those who have to wait for them",
    "Perhaps you've been focusing too much on that one thing..",
    "Pick a path with heart.",
    "Plan your work and work your plan.",
    "Poverty is no disgrace.",
    "Pray to God, but row towards shore.",
    "Present your best ideas today to an eager and welcoming audience.",
    "Prosperity makes friends and adversity tries them.",
    "Punctuality is the politeness of kings and the duty of gentle people everywhere.",
    "Put your mind into planning today. Look into the future.",
    "Put your unhappiness aside. Life is beautiful, be happy.",
    "Questions provide the key to unlocking our unlimited potential.",
    "Rarely do great beauty and great virtue dwell together as they do in you.",
    "Reading to the mind is what exercise is to the body.",
    "Remember the fate of the early Worm.",
    "Remember this: duct tape can fix anything, so don't worry about messing things up.",
    "Rest has a peaceful effect on your physical and emotional health.",
    "Rest is a good thing, but boredom is its brother.",
    "Right now there's an energy pushing you in a new direction.",
    "Rivers need springs.",
    "See the light at the end of the tunnel.",
    "Seek out the significance of your problem at this time. Try to understand.",
    "Seize every second of your life and savor it.",
    "Service is the rent we pay for the privilege of living on this planet.",
    "Share your hapiness with others today.",
    "Simplicity and clearity should be the theme in your dress.",
    "Sing and rejoice, fortune is smiling on you.",
    "Smile. Tomorrow is another day.",
    "Some pursue happiness; you create it.",
    "Someday everything will all make perfect sense",
    "Someone close to you is waiting for you to call.",
    "Sometimes the object of the journey is not the end, but the journey itself.",
    "Sometimes travel to new places leads to great transformation.",
    "Sometimes you just need to lay on the floor.",
    "Soon life will become more interesting",
    "Soon you will be sitting on top of the world.",
    "Soon, a visitor shall delight you.",
    "Spring has sprung. Life is blooming.",
    "Stay to your inner-self, you will benefit in many ways.",
    "Stay true to those who would do the same for you.",
    "Stop searching forever, happiness is just next to you. ",
    "Stop thinking about the road not taken and pave over the one you did.",
    "Stop wishing. Start doing.",
    "Success is the sum of my unique visions realized by the sweat of perseverance.",
    "Take a minute and let it ride, then take a minute to let it breeze.",
    "Take control of your life rather than letting things happen just like that!",
    "Take it easy",
    "Take the chance while you still have the choice.",
    "Teamwork: the fuel that allows common people attain uncommon results.",
    "Tell them before it's too late...",
    "Tell them what you really think. Otherwise, nothing will change.",
    "The best is yet to come.",
    "The best prophet of the future is the past",
    "The best things in life aren't things.",
    "The best way to give credit is to give it away.",
    "The cooler you think you are the dumber you look",
    "The cure for grief is motion.",
    "The days that make us happy make us wise.",
    "The dream is within you.",
    "The earth is a school learn in it.",
    "The expanse of your intelligence is a void no universe could ever fill.",
    "The eyes believe themselves; the ears believe other people.",
    "The finest men like the finest steels have been tempered in the hottest furnace.",
    "The greatest precept is continual awareness.",
    "The greatest risk is not taking one.",
    "The Greatest War Sometimes Isn't On The Battlefield But Against Oneself.",
    "The harder you try to not be like your parents, the more likely you will become them",
    "The human spirit is stronger than anything that can happen to it.",
    "The important thing is to never stop questioning.",
    "The joyful energy of the day will have a positive affect on you.",
    "The leader seeks to communicate his vision to his followers.",
    "The love of your life is sitting across from you.",
    "The love of your life is stepping into your planet this summer.",
    "The man on the top of the mountain did not fall there.",
    "The man who waits till tomorrow, misses the opportunities of today.",
    "The measure of time to your next goal is the measure of your discipline.",
    "The most important thing in communication is to hear what isn’t being said.",
    "The object of your desire comes closer.",
    "The one who snores will always fall asleep first.",
    "The only certainty is that nothing is certain.",
    "The person you desire feels the same about you.",
    "The pleasure of what we enjoy is lost by wanting more",
    "The possibility of a career change is near.",
    "The problem with resisting temptation is that it may never come again.",
    "the project on your mind will soon gain momentum",
    "The race is not always to the swift, but to those who keep on running.",
    "The secret of getting ahead is getting started.",
    "The secret of staying young is good health and lying about your age.",
    "The simplest answer is to act.",
    "The smart thing to do is to begin trusting your intuitions.",
    "The time is alway right to do what is right.",
    "The time is right to make new friends.",
    "The troubles you have now will pass away quickly.",
    "The ultimate test of a relationship is to disagree but to hold hands.",
    "The Wheel of Good Fortune is finally turning in your direction!",
    "The wise are aware of their treasure, while fools follow their vanity",
    "The world is always ready to receive talent with open arms.",
    "The world may be your oyster, but that doesn't mean you'll get its pearl.",
    "There are big changes ahead for you. They will be good ones!",
    "There are lessons to be learned by listening to others.",
    "There are many new opportunities that are being presented to you.",
    "There are no limitations to the mind except those we aknowledge.",
    "There are no shortcuts to any place worth going",
    "There is a prospect of a thrilling time ahead for you.",
    "There is a time to be practical now.",
    "There is always a way - if you are committed.",
    "There is no greater pleasure than seeing your loved ones prosper.",
    "There is someone rather annoying in your life that you need to listen to.",
    "There will be a happy romance for you shortly.",
    "They say you are stubborn; you call it persistence.",
    "Things may come to those who wait, but only the things left by those who hustle.",
    "Think of how you can assist on a problem, not who to blame.",
    "Think of mother's exhortations more.",
    "Think you can. Think you can't. Either way, you'll be right.",
    "This is really a lovely day. Congratulations!",
    "Those grapes you cannot taste are always sour.",
    "Those who bring sunshine to the lives of others cannot keep it from themselves.",
    "Those who walk in other's tracks leave no footprints.",
    "Time may fly by. But Memories don't.",
    "To be old and wise, you must first be young and stupid.",
    "To build a better world, start in your community.",
    "To courageously shoulder the responsibility of one's mistake is character.",
    "To determine whether someone is beautiful is not by looking at their appearance, but their heart.",
    "To effect the quality of the day is no small achievement.",
    "To forgive others one more time is to create one more blessing for yourself.",
    "To make the cart go, you must grease the wheels.",
    "Today is an ideal time to water your parsonal garden.",
    "Today is going to be a disasterous day, be prepared!",
    "Today is the tomorrow we worried about yesterday",
    "Today it's up to you to create the peacefulness you long for.",
    "Today you shed your last tear. Tomorrow fortune knocks at your door.",
    "today you should be a passenger. Stay close to a driver for a day.",
    "Tomorrow Morning,Take a Left Turn As Soon As You Leave Home",
    "Tomorrow, take a moment to do something just for yourself.",
    "TOO MANY PEOPLE VOLUNTEER TO CARRY THE STOOL WHEN ITS TIME TO MOVE THE PIANO",
    "Traveling more often is important for your health and happiness.",
    "Traveling this year will bring your life into greater perspective.",
    "Treasure what you have.",
    "True wisdom is found in happiness.",
    "Trust your intuition.",
    "Trust your intuition. The universe is guiding your life.",
    "Truth is an unpopular subject. Because it is unquestionably correct.",
    "Try everything once, even the things you don't think you will like.",
    "Try? No! Do or do not, there is no try.",
    "Two small jumps are sometimes better than one big leap.",
    "Unleash your life force.",
    "Use your head, but live in your heart.",
    "Use your instincts now.",
    "Use your talents. That's what they are intended for. ",
    "Virtuous find joy while Wrongdoers find grieve in their actions.",
    "Vision is the art of seeing what is invisible to others.",
    "Volition, Strength, Languages, Freedom and Power rests in you.",
    "We all have extraordinary coded within us, waiting to be released.",
    "We are here to love each other, serve each other and uplift each other.",
    "We can't help everyone. But everyone can help someone.",
    "We cannot change the direction of the wind, but we can adjust our sails.",
    "We cannot direct the wind but we can adjust the sails.",
    "Wealth awaits you very soon.",
    "Welcome the change coming into your life.",
    "Well-arranged time is the surest sign of a well-arranged mind.",
    "What breaks in a moment may take years to mend.",
    "What ends on hope does not end at all.",
    "What goes around comes around.",
    "What's vice today may be virtue tomorow.",
    "Whatever your goal is in life, embrace it, visualize it, and it will be yours.",
    "When all else seems to fail, smile for today and just love someone.",
    "When fear hurts you, conquer it and defeat it!",
    "WHEN FIRE AND WATER GO TO WAR WATER ALWAYS WINS.",
    "When in doubt, let your instincts guide you.",
    "When the moment comes, take the top one.",
    "When you can't naturally feel upbeat it can sometimes help you to act as if you did.",
    "When you look down, all you see is dirt, so keep looking up.",
    "When you're about to turn your heart into a stone remember: you do not walk alone.",
    "Whenever possible, keep it simple.",
    "While you have this day, fill it with life. While you're in this moment, give it your own special meaning and purpose and joy.",
    "Wisdom is on her way to you.",
    "Wise sayings often fall on barren ground, but a kind word is never thrown away.",
    "Working hard will make you live a happy life.",
    "Working out the kinks today will make for a better tomorrow.",
    "You already know the answer to the questions lingering inside your head.",
    "You always know the right times to be assertive or to simply wait.",
    "You are a lover of words; One day you will write a book.",
    "You are a person of culture.",
    "You are a person of strong sense of duty",
    "You are a persoon with a good sense of justice, now it's time to act like it.",
    "You are admired by everyone for your talent and ability.",
    "You are admired for your adventuous ways.",
    "You are always welcome in any gathering.",
    "You are blessed, today is the day to bless others.",
    "You are broad minded and socially active.",
    "You are cautious in showing your true self to others.",
    "You are contemplating some action which will bring credit upon you",
    "You are extremely loved. Don't worry :)",
    "You are far more influential than you think.",
    "You are given the chance to take part in an exciting adventure.",
    "You are never selfish with your advice or your help.",
    "You are not a person who can be ignored.",
    "You are not judged by your efforts you put in; you are judged on your performance.",
    "You are offered the dream of a lifetime. Say yes!",
    "You are one of the people who 'goes places in life.'",
    "You are talented in many ways.",
    "You are the controller of your destiny.",
    "You are a person of righteousness and integrity.",
    "You are the master of every situation.",
    "You are very grateful for the small pleasures of life.",
    "You are very talented in many ways.",
    "You are vigorous in words and action.",
    "You are what you are; understand yourself before you react",
    "You are worth loving, you are also worth the effort it takes to love you",
    "You believe in the goodness of mankind.",
    "You can choose, right now and in every moment, to put your powerful and effective abilities to purposeful use. There is always something you can do, no matter what the situation may be, that will move your life forward.",
    "You can fix it with a little extra energy and a positive attitude.",
    "You can make your own happiness.",
    "You can never be certain of success, but you can be certain of failure if you never try.",
    "You can open doors with your charm and patience.",
    "You can still love what you can not have in life.",
    "You cannot become rich except by enriching others.",
    "you cant go down the right path with out first discovering the path to go down",
    "You create enthusiasm around you.",
    "You create your own stage ... the audience is waiting.",
    "You don't get harmony when everyone sings the same note.",
    "You don't need talent to gain experience.",
    "You have a curious smile and a mysterious nature.",
    "You have a deep appreciation of the arts and music.",
    "You have a deep interest in all that is artistic.",
    "You have a fine capacity for the enjoyment of life.",
    "You have a flair for adding a fanciful dimension to any story.",
    "You have a quiet and unobtrusive nature.",
    "You have a reputation for being straightforward and honest.",
    "You have a strong desire for a home and your family interests come first.",
    "You have an important new business development shaping up.",
    "You have an unusual equipment for success, use it properly.",
    "You have an unusually magnetic personality.",
    "You know where you are going and how to get there",
    "You may be disappointed if you fail, but you are doomed if you don't try.",
    "You must try, or hate yourself for not trying.",
    "You need to live authentically, and you can't ignore that.",
    "You never hesitate to tackle the most difficult problems.",
    "You only need look to your own reflection for inspiration. Because you are Beautiful!",
    "You should be able to make money and hold on to it.",
    "You should be able to undertake and complete anything",
    "You try hard, never to fail. You don't, never to win.",
    "You will achieve all your desires and pleasures.",
    "You will always be successful in your professional career",
    "You will always be surrounded by true friends",
    "You will always get what you want through your charm and personality.",
    "You will always have good luck in your personal affairs.",
    "You will be called to fill a position of high honor and responsibility.",
    "You will be forced to face fear, but if you do not run, fear will be afraid of you.",
    "You will be rewarded for being a good listener in the next week.",
    "You will be rewarded for your patience and understanding.",
    "You will be selected for a promotion because of your accomplishments.",
    "You will be sharing great news with all people you love",
    "You will be successful in love.",
    "You will be successful in your work",
    "You will be traveling and coming into a fortune. ",
    "You will become better acquainted with a coworker.",
    "You will become great if you believe in yourself.",
    "You will conquer obstacles to achieve success.",
    "You will discover your hidden talents.",
    "You will enjoy good health, you will be surrounded by luxury",
    "You will enjoy razor-sharp spiritual vision today.",
    "You will have a bright future.",
    "You will have a long and wealthy life.",
    "You will have a pleasant surprise",
    "You will have good luck and overcome many hardships.",
    "You will have many happy days soon.",
    "You will have unexpected great good luck.",
    "You will live long and enjoy life.",
    "You will make heads turn.",
    "You will make many changes before settling down happily.",
    "You will outdistance all your competitors.",
    "You will overcome difficult times.",
    "You will plant the smallest seed and it will become the greatest and most mighty tree in the world.",
    "You will prosper in the field of wacky inventions.",
    "You will recieve a gift from someone that cares about you.",
    "You will recieve some high prize or award.",
    "You will soon be honored by someone you respect.",
    "You will soon be surrounded by good friends and laughter.",
    "You will soon discover a major truth about the one you love most.",
    "You will soon embark on a business venture.",
    "You will soon emerge victorious from the maze you've been traveling in.",
    "You will soon witness a miracle.",
    "you will spend old age in confort and material wealth",
    "You will take a pleasant journey to a place far away.",
    "you will think for yourself when you stop letting others think for you",
    "You will travel to many exotic places in your lifetime.",
    "You will win success in whatever you adopt.",
    "Your true love will show themself to you under the moonlight.",
    "You've got what it takes, but it will take everything you've got!",
    "Your ability for accomplishment will be followed by success.",
    "Your co-workers take pleasure in your great sense of creativity.",
    "Your dearest wish will come true.",
    "Your dream will come true when you least expect it.",
    "Your dynamic eyes have attracted a secret admirer.",
    "Your emotional currents are flowing powerfully now.",
    "Your emotional nature is strong and sensitive.",
    "YOUR FAILURES WILL LEAD YOU TO YOUR SUCCESS.",
    "Your fondest dream will come true within this year.",
    "Your future will be happy and productive.",
    "Your golden opportunity is coming shortly.",
    "Your happiness is intertwined with your outlook on life.",
    "Your hard work will get payoff today.",
    "Your high-minded principles spell success.",
    "Your life becomes more and more of an adventure!",
    "Your life does not get better by chance, it gets better by change.",
    "Your life will be filled with magical moments.",
    "Your life will prosper only if you acknowledge your faults and work to reduce them.",
    "Your many hidden talents will become obvious to those around you.",
    "Your pain is the breaking of the shell that encloses your understanding.",
    "Your passions sweep you away.",
    "Your present question marks are going to succeed.",
    "Your problem just became your stepping stone. Catch the moment.",
    "Your secret desire to completely change your life will manifest.",
    "Your skill will accomplish what the force of many cannot.",
    "Your smile brings happiness to everyone you meet.",
    "Your succeess will astonish everyone.",
    "Your tongue is your ambassador.",
    "Your way of doing what other people do their way is what makes you special.",
    "Your wish will come true.",
]
